services:
  search-credit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-credit
    ports:
      - "8189:8189"
    depends_on:
      - postgres
      - kafka
    networks:
      - search-credit-network

  postgres:
    image: postgres:15
    container_name: search-credit-postgres
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: search_credit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - search-credit-network

  zookeeper:
    image: zookeeper:3.8
    container_name: search-credit-zookeeper
    ports:
      - "2182:2181"
    environment:
      ZOO_CLIENT_PORT: 2181
      ZOO_TICK_TIME: 2000
    networks:
      - search-credit-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: search-credit-kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://search-credit-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - search-credit-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: search-credit-kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: search-credit-kafka:9092
    depends_on:
      - kafka
    networks:
      - search-credit-network

volumes:
  pgdata:

networks:
  search-credit-network:
    external: true
